# Generated by Django 4.1.5 on 2023-01-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'이미 사용중인 이메일입니다'}, max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
