# Generated by Django 4.1.5 on 2023-01-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(
                error_messages={"이미 사용중인 이메일입니다"},
                max_length=254,
                unique=True,
                verbose_name="이메일",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="password",
            field=models.CharField(max_length=30, verbose_name="패스워드"),
        ),
    ]
