# Generated by Django 4.1.5 on 2023-01-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_usermodel_email_alter_usermodel_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
    ]
